### ISSUE TITLE
download

### ISSUE THREAD

**Issue by shahinesi** [michaelcunningham19/video-speech-recognition#6]
Why only download it once !?
I want a list of videos and sounds!
Also the movie has no image and only sound!

![image](https://user-images.githubusercontent.com/16535600/72679865-c15a1d00-3ac8-11ea-91ab-8ebb229ee958.png)

**Comment by michaelcunningham19** [comment]
Hi @shahinesi

That's expected, and these files in your screenshot are the audio data that was extracted from the mp4 data in the stream. The client-strategy retrieves audio bytes from the player in the user's browser, and forwards that to the small backend component which communicates with Google Cloud Platform (GCP).

I recommend avoiding the client-strategy that exists under `./archive` as it is really only intended for reference purposes.
